#!/usr/bin/env node

/**
 * Orchestrator Agent Setup Script
 * 
 * Interactive configuration for the entry file that agents should read
 * to understand the project context.
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const skillDir = path.dirname(__dirname);
const configFile = path.join(skillDir, '.orchestrator');

// Common entry file options
const defaultOptions = [
  { name: 'README.md', description: 'Standard project documentation' },
  { name: 'DOCS.md', description: 'Extended documentation file' },
  { name: 'AGENTS.md', description: 'Agent-specific instructions' },
  { name: 'PROJECT.md', description: 'Project overview and guidelines' },
  { name: 'CONTEXT.md', description: 'Context and background info' }
];

console.log(`
╔═══════════════════════════════════════════════════════════╗
║         Orchestrator Agent - Configuration Setup           ║
╚═══════════════════════════════════════════════════════════╝

This script configures which file agents should read to understand
your project at the beginning of each conversation.

Default: README.md
`);

// Check if config already exists
let currentConfig = null;
if (fs.existsSync(configFile)) {
  try {
    const content = fs.readFileSync(configFile, 'utf8');
    const match = content.match(/entry_file:\s*(.+)/);
    if (match) {
      currentConfig = match[1].trim();
      console.log(`⚠️  Existing configuration found: ${currentConfig}\n`);
    }
  } catch (e) {
    // Ignore read errors
  }
}

// Auto-detect available files in current directory
const availableFiles = defaultOptions
  .map(opt => opt.name)
  .filter(file => fs.existsSync(path.join(process.cwd(), file)));

if (availableFiles.length > 0) {
  console.log('📁 Detected in current directory:', availableFiles.join(', '));
  console.log('');
}

console.log('Select your preferred entry file:\n');
defaultOptions.forEach((opt, idx) => {
  const marker = availableFiles.includes(opt.name) ? ' ✓' : '';
  console.log(`${idx + 1}. ${opt.name}${marker}`);
  console.log(`   ${opt.description}`);
  console.log('');
});

console.log(`${defaultOptions.length + 1}. Custom (specify your own)`);
console.log('');

const askChoice = () => {
  const prompt = currentConfig 
    ? `Enter choice (1-${defaultOptions.length + 1}) or press Enter to keep "${currentConfig}": `
    : `Enter choice (1-${defaultOptions.length + 1}, default is 1): `;
  
  rl.question(prompt, (answer) => {
    // Use current config if user presses Enter
    if (!answer.trim() && currentConfig) {
      console.log(`\n✅ Keeping existing configuration: ${currentConfig}`);
      rl.close();
      return;
    }

    const choice = parseInt(answer.trim()) || 1;
    
    if (choice >= 1 && choice <= defaultOptions.length) {
      const selectedFile = defaultOptions[choice - 1].name;
      saveConfig(selectedFile);
    } else if (choice === defaultOptions.length + 1) {
      askCustomFile();
    } else {
      console.log('\n❌ Invalid choice. Please try again.\n');
      askChoice();
    }
  });
};

const askCustomFile = () => {
  rl.question('\nEnter custom filename (e.g., ONBOARDING.md): ', (filename) => {
    const cleanFile = filename.trim();
    if (!cleanFile) {
      console.log('\n❌ Filename cannot be empty. Using default: README.md');
      saveConfig('README.md');
    } else {
      saveConfig(cleanFile);
    }
  });
};

const saveConfig = (entryFile) => {
  const config = `# Orchestrator Agent Configuration
# Generated by setup.js

entry_file: ${entryFile}

# This file tells the Orchestrator Agent which document agents should
# read to understand your project context. Sub-agents will be instructed
# to read this file before starting any work.
#
# To change this later, either:
# 1. Re-run: node scripts/setup.js
# 2. Manually edit this file
`;

  try {
    fs.writeFileSync(configFile, config, 'utf8');
    console.log(`\n✅ Configuration saved!`);
    console.log(`   Entry file set to: ${entryFile}`);
    console.log(`   Config location: ${configFile}`);
    console.log(`\n📝 Sub-agents will now be instructed to read "${entryFile}"`);
    console.log('   at the start of each conversation.\n');
    
    // Check if file exists in current project
    const projectFile = path.join(process.cwd(), entryFile);
    if (!fs.existsSync(projectFile)) {
      console.log(`⚠️  Warning: ${entryFile} was not found in the current directory.`);
      console.log('   Make sure to create this file in your project.\n');
    }
    
    rl.close();
  } catch (error) {
    console.error('\n❌ Error saving configuration:', error.message);
    console.error('   You may need to run this script with appropriate permissions.\n');
    process.exit(1);
  }
};

// Start the interactive prompt
askChoice();

// Handle Ctrl+C gracefully
rl.on('SIGINT', () => {
  console.log('\n\n❌ Setup cancelled. No changes made.\n');
  process.exit(0);
});
